// Tests for sync.sh — the copy step from plugin sandbox storage into the site
// repo. The contract is narrow but load-bearing: everything lands under
// _incoming/, and the site's generated directories are never touched.
//
// These drive the real script through bash against throwaway directories,
// because the rest of the suite covers index.js only and would not catch a
// regression here.

const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const SYNC_SH = path.resolve(__dirname, '../../sync.sh');
const PLUGIN_ID = 'logseq-alfolio-export';
const EXPORT_PREFIX = '_logseq_export';

/** A graph whose sandbox storage holds a complete export. */
function makeGraph(root, { withBlog = true, withManifest = true, manifestContent = null } = {}) {
  const exportDir = path.join(
    root, 'graph', '.logseq', 'plugins', 'storages', PLUGIN_ID, EXPORT_PREFIX,
  );
  fs.mkdirSync(exportDir, { recursive: true });

  fs.writeFileSync(path.join(exportDir, 'cv.yml'), 'experience:\n  - position: Engineer\n');
  fs.writeFileSync(path.join(exportDir, 'profile.yml'), 'name: Test Person\n');
  fs.writeFileSync(path.join(exportDir, 'personal.yml'), 'music:\n  title: Music\n');
  fs.writeFileSync(path.join(exportDir, 'publication_overrides.yml'), 'key2024:\n  selected: true\n');

  if (withManifest) {
    // sync.sh copies exactly what the manifest lists, so the fixture manifest
    // has to describe the staged files the way a real contract-v1 export does.
    const listed = [
      'cv.yml', 'profile.yml', 'personal.yml', 'publication_overrides.yml', 'manifest.json',
      ...(withBlog ? ['blog/2026-01-02-a-post.md'] : []),
    ];
    fs.writeFileSync(
      path.join(exportDir, 'manifest.json'),
      manifestContent ?? JSON.stringify({
        schema_version: 1,
        exported_at: '2026-01-01T00:00:00.000Z',
        files: listed,
        counts: { experience: 1 },
      }, null, 2),
    );
  }
  if (withBlog) {
    fs.mkdirSync(path.join(exportDir, 'blog'), { recursive: true });
    fs.writeFileSync(path.join(exportDir, 'blog', '2026-01-02-a-post.md'), '---\ntitle: "A Post"\n---\n');
  }
  return path.join(root, 'graph');
}

/** A site checkout with generated files that must survive the sync untouched. */
const SENTINELS = {
  '_data/cv.yml': 'cv:\n  - title: GENERATED BY TRANSFORM\n',
  '_data/icon_map.yml': 'up: assets/img/logos/up.png\n',
  '_posts/2020-01-01-existing.md': '---\ntitle: Existing\n---\n',
  '_bibliography/papers.bib': '@article{key2024}\n',
};

function makeSite(root) {
  const siteDir = path.join(root, 'site');
  for (const [rel, content] of Object.entries(SENTINELS)) {
    const abs = path.join(siteDir, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content);
  }
  return siteDir;
}

/**
 * Run sync.sh, throwing on a non-zero exit. `stderrOut`, when given, collects
 * the script's stderr so a test can assert on warnings.
 */
function runSync(args, env = {}, stderrOut = null) {
  const result = spawnSync('bash', [SYNC_SH, ...args], {
    encoding: 'utf8',
    // Strip inherited GRAPH_DIR/SITE_DIR so the test controls them entirely.
    // Node omits undefined-valued keys when building the child's environment.
    env: { ...process.env, GRAPH_DIR: undefined, SITE_DIR: undefined, ...env },
  });
  if (stderrOut) stderrOut.push(result.stderr);
  if (result.status !== 0) {
    throw new Error(`sync.sh exited ${result.status}\n${result.stderr}`);
  }
  return result.stdout;
}

describe('sync.sh', () => {
  let tmp;

  beforeEach(() => {
    tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'alfolio-sync-'));
  });

  afterEach(() => {
    fs.rmSync(tmp, { recursive: true, force: true });
  });

  describe('destination', () => {
    test('copies every exported file into _incoming/', () => {
      const graph = makeGraph(tmp);
      const site = makeSite(tmp);

      runSync(['--graph', graph, '--site', site]);

      const incoming = path.join(site, '_incoming');
      for (const f of ['cv.yml', 'profile.yml', 'personal.yml', 'publication_overrides.yml', 'manifest.json']) {
        expect(fs.existsSync(path.join(incoming, f))).toBe(true);
      }
      expect(fs.existsSync(path.join(incoming, 'blog', '2026-01-02-a-post.md'))).toBe(true);
    });

    test('copies file contents verbatim', () => {
      const graph = makeGraph(tmp);
      const site = makeSite(tmp);

      runSync(['--graph', graph, '--site', site]);

      const exportDir = path.join(graph, '.logseq/plugins/storages', PLUGIN_ID, EXPORT_PREFIX);
      const incoming = path.join(site, '_incoming');
      for (const f of ['cv.yml', 'manifest.json']) {
        expect(fs.readFileSync(path.join(incoming, f), 'utf8'))
          .toBe(fs.readFileSync(path.join(exportDir, f), 'utf8'));
      }
    });

    test('keeps the manifest named manifest.json', () => {
      const graph = makeGraph(tmp);
      const site = makeSite(tmp);

      runSync(['--graph', graph, '--site', site]);

      expect(fs.existsSync(path.join(site, '_incoming', 'manifest.json'))).toBe(true);
      expect(fs.existsSync(path.join(site, '_data', 'export_manifest.json'))).toBe(false);
    });
  });

  describe('generated directories are never written', () => {
    test('leaves _data/, _posts/ and _bibliography/ byte-identical', () => {
      const graph = makeGraph(tmp);
      const site = makeSite(tmp);

      runSync(['--graph', graph, '--site', site]);

      for (const [rel, original] of Object.entries(SENTINELS)) {
        expect(fs.readFileSync(path.join(site, rel), 'utf8')).toBe(original);
      }
    });

    test('creates no files outside _incoming/', () => {
      const graph = makeGraph(tmp);
      const site = makeSite(tmp);

      const before = listFiles(site);
      runSync(['--graph', graph, '--site', site]);
      const added = listFiles(site).filter((f) => !before.includes(f));

      expect(added.length).toBeGreaterThan(0);
      for (const f of added) {
        expect(f.startsWith('_incoming/')).toBe(true);
      }
    });

    test('does not create _data/ or _posts/ when the site lacks them', () => {
      const graph = makeGraph(tmp);
      const site = path.join(tmp, 'bare-site');
      fs.mkdirSync(site, { recursive: true });

      runSync(['--graph', graph, '--site', site]);

      expect(fs.existsSync(path.join(site, '_data'))).toBe(false);
      expect(fs.existsSync(path.join(site, '_posts'))).toBe(false);
      expect(fs.existsSync(path.join(site, '_incoming', 'cv.yml'))).toBe(true);
    });
  });

  // _incoming/ is not exclusively the plugin's: the site keeps README.md there
  // and papers.src.bib is staged by hand from Zotero. So stale files are pruned
  // by the *previous manifest's* file list — exactly what the last export
  // owned — and never by clearing the directory.
  describe('pruning stale files', () => {
    /** Seed _incoming/ as if a previous export had staged `files`. */
    function seedIncoming(site, files, { manifest = null } = {}) {
      const incoming = path.join(site, '_incoming');
      for (const rel of files) {
        const abs = path.join(incoming, rel);
        fs.mkdirSync(path.dirname(abs), { recursive: true });
        fs.writeFileSync(abs, `stale ${rel}\n`);
      }
      fs.mkdirSync(incoming, { recursive: true });
      fs.writeFileSync(
        path.join(incoming, 'manifest.json'),
        manifest ?? JSON.stringify({
          schema_version: 1,
          exported_at: '2025-01-01T00:00:00.000Z',
          files: [...files, 'manifest.json'],
        }),
      );
      return incoming;
    }

    test('removes a file the previous export owned and this one does not', () => {
      const graph = makeGraph(tmp);
      const site = makeSite(tmp);
      const incoming = seedIncoming(site, ['blog/2020-01-01-dropped.md', 'cv.yml']);

      runSync(['--graph', graph, '--site', site]);

      expect(fs.existsSync(path.join(incoming, 'blog/2020-01-01-dropped.md'))).toBe(false);
      // Still listed by the new export, so it is overwritten rather than removed.
      expect(fs.readFileSync(path.join(incoming, 'cv.yml'), 'utf8')).toContain('position: Engineer');
    });

    test('never touches a file the plugin does not own', () => {
      const graph = makeGraph(tmp);
      const site = makeSite(tmp);
      const incoming = seedIncoming(site, ['blog/2020-01-01-dropped.md']);
      // Neither is plugin output: README.md is the site's, papers.src.bib is
      // staged by hand from Zotero on a different cadence.
      fs.writeFileSync(path.join(incoming, 'README.md'), '# staging area\n');
      fs.writeFileSync(path.join(incoming, 'papers.src.bib'), '@article{key2024}\n');

      runSync(['--graph', graph, '--site', site]);

      expect(fs.readFileSync(path.join(incoming, 'README.md'), 'utf8')).toBe('# staging area\n');
      expect(fs.readFileSync(path.join(incoming, 'papers.src.bib'), 'utf8')).toBe('@article{key2024}\n');
    });

    test.each([
      ['unparseable JSON', 'NOT JSON{'],
      ['no files list', JSON.stringify({ schema_version: 1 })],
      ['an unknown schema_version', JSON.stringify({ schema_version: 99, files: ['blog/x.md'] })],
    ])('prunes nothing when the previous manifest has %s, and says so', (_label, manifest) => {
      const graph = makeGraph(tmp);
      const site = makeSite(tmp);
      const incoming = seedIncoming(site, ['blog/2020-01-01-dropped.md'], { manifest });

      const stderr = [];
      runSync(['--graph', graph, '--site', site], {}, stderr);

      expect(fs.existsSync(path.join(incoming, 'blog/2020-01-01-dropped.md'))).toBe(true);
      expect(stderr.join('')).toMatch(/pruning nothing|nothing to prune/);
    });

    test('prunes nothing on a first sync, without complaining', () => {
      const graph = makeGraph(tmp);
      const site = makeSite(tmp);

      const stderr = [];
      runSync(['--graph', graph, '--site', site], {}, stderr);

      expect(stderr.join('')).toMatch(/nothing to prune/);
      expect(fs.existsSync(path.join(site, '_incoming', 'cv.yml'))).toBe(true);
    });

    test('an already-absent stale entry is not an error', () => {
      const graph = makeGraph(tmp);
      const site = makeSite(tmp);
      const incoming = seedIncoming(site, []);
      fs.writeFileSync(path.join(incoming, 'manifest.json'), JSON.stringify({
        schema_version: 1,
        files: ['blog/never-existed.md', 'manifest.json'],
      }));

      expect(() => runSync(['--graph', graph, '--site', site])).not.toThrow();
    });

    test('ignores a path that tries to escape _incoming/', () => {
      const graph = makeGraph(tmp);
      const site = makeSite(tmp);
      const incoming = seedIncoming(site, [], {
        manifest: JSON.stringify({
          schema_version: 1,
          files: ['../../_data/cv.yml', 'manifest.json'],
        }),
      });
      const sentinel = path.join(site, '_data/cv.yml');

      const stderr = [];
      runSync(['--graph', graph, '--site', site], {}, stderr);

      expect(fs.readFileSync(sentinel, 'utf8')).toBe(SENTINELS['_data/cv.yml']);
      expect(stderr.join('')).toMatch(/unsafe path/);
      expect(fs.existsSync(path.join(incoming, 'cv.yml'))).toBe(true);
    });
  });

  // The manifest is the commit point: written last, a crash leaves the previous
  // manifest intact and a re-run is still correct.
  describe('the manifest is written last', () => {
    test('a missing staged file aborts before the manifest is replaced', () => {
      const graph = makeGraph(tmp);
      const site = makeSite(tmp);
      const incoming = seedPrevious(site);
      // The new export lists a file that is not on disk — a half-finished write.
      const exportDir = path.join(graph, '.logseq/plugins/storages', PLUGIN_ID, EXPORT_PREFIX);
      fs.rmSync(path.join(exportDir, 'profile.yml'));

      expect(() => runSync(['--graph', graph, '--site', site])).toThrow();

      // The previous manifest survives, so the next run still knows what the
      // last export owned.
      expect(JSON.parse(fs.readFileSync(path.join(incoming, 'manifest.json'), 'utf8')).exported_at)
        .toBe('2025-01-01T00:00:00.000Z');
    });

    function seedPrevious(site) {
      const incoming = path.join(site, '_incoming');
      fs.mkdirSync(incoming, { recursive: true });
      fs.writeFileSync(path.join(incoming, 'manifest.json'), JSON.stringify({
        schema_version: 1,
        exported_at: '2025-01-01T00:00:00.000Z',
        files: ['cv.yml', 'manifest.json'],
      }));
      return incoming;
    }
  });

  describe('refuses to guess a destination', () => {
    test('exits non-zero when --site is omitted', () => {
      const graph = makeGraph(tmp);

      expect(() => runSync(['--graph', graph])).toThrow();
    });

    test('exits non-zero when the site directory does not exist', () => {
      const graph = makeGraph(tmp);

      expect(() => runSync(['--graph', graph, '--site', path.join(tmp, 'nope')])).toThrow();
    });

    test('reports a flag given without a value instead of failing silently', () => {
      const site = makeSite(tmp);

      const stderr = [];
      expect(() => runSync(['--site', site, '--graph'], {}, stderr)).toThrow();
      expect(stderr.join('')).toMatch(/--graph requires a path/);
    });

    test('honours SITE_DIR from the environment', () => {
      const graph = makeGraph(tmp);
      const site = makeSite(tmp);

      runSync(['--graph', graph], { SITE_DIR: site });

      expect(fs.existsSync(path.join(site, '_incoming', 'cv.yml'))).toBe(true);
    });
  });

  describe('incomplete exports', () => {
    test('exits non-zero when the export directory is missing', () => {
      const site = makeSite(tmp);

      expect(() => runSync(['--graph', path.join(tmp, 'no-graph'), '--site', site])).toThrow();
      expect(fs.existsSync(path.join(site, '_incoming'))).toBe(false);
    });

    test('exits non-zero when manifest.json is missing', () => {
      const graph = makeGraph(tmp, { withManifest: false });
      const site = makeSite(tmp);

      expect(() => runSync(['--graph', graph, '--site', site])).toThrow();
      expect(fs.existsSync(path.join(site, '_incoming'))).toBe(false);
    });

    // The manifest is now the copy plan, so an unreadable one is fatal *before*
    // anything is written — which is where the PR 0 review said a validity
    // check belongs, rather than as a side effect after the copy.
    test('refuses to copy when manifest.json is not valid JSON', () => {
      const graph = makeGraph(tmp, { manifestContent: 'NOT JSON{' });
      const site = makeSite(tmp);

      expect(() => runSync(['--graph', graph, '--site', site])).toThrow();
      expect(fs.existsSync(path.join(site, '_incoming', 'cv.yml'))).toBe(false);
    });

    test('refuses an export whose manifest lists no files', () => {
      const graph = makeGraph(tmp, {
        manifestContent: JSON.stringify({ schema_version: 1, exported_at: '2026-01-01T00:00:00.000Z' }),
      });
      const site = makeSite(tmp);

      const stderr = [];
      expect(() => runSync(['--graph', graph, '--site', site], {}, stderr)).toThrow();
      expect(stderr.join('')).toMatch(/no files list/);
    });

    test('handles a graph path containing a quote', () => {
      const quoted = path.join(tmp, "pedro's graph");
      fs.mkdirSync(quoted, { recursive: true });
      const graph = makeGraph(quoted);
      const site = makeSite(tmp);

      const stdout = runSync(['--graph', graph, '--site', site]);

      expect(stdout).toMatch(/Export from: 2026-01-01/);
      expect(fs.existsSync(path.join(site, '_incoming', 'cv.yml'))).toBe(true);
    });

    test('succeeds when there are no blog posts', () => {
      const graph = makeGraph(tmp, { withBlog: false });
      const site = makeSite(tmp);

      runSync(['--graph', graph, '--site', site]);

      expect(fs.existsSync(path.join(site, '_incoming', 'cv.yml'))).toBe(true);
      expect(fs.existsSync(path.join(site, '_incoming', 'blog'))).toBe(false);
    });
  });
});

/** Every file under `dir`, as paths relative to it. */
function listFiles(dir, prefix = '') {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) out.push(...listFiles(path.join(dir, entry.name), rel));
    else out.push(rel);
  }
  return out;
}
