// Tests for sync.sh — the copy step from plugin sandbox storage into the site
// repo. The contract is narrow but load-bearing: everything lands under
// _incoming/, and the site's generated directories are never touched.
//
// These drive the real script through bash against throwaway directories,
// because the rest of the suite covers index.js only and would not catch a
// regression here.

const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const SYNC_SH = path.resolve(__dirname, '../../sync.sh');
const PLUGIN_ID = 'logseq-alfolio-export';
const EXPORT_PREFIX = '_logseq_export';

/** A graph whose sandbox storage holds a complete export. */
function makeGraph(root, { withBlog = true, withManifest = true, manifestContent = null } = {}) {
  const exportDir = path.join(
    root, 'graph', '.logseq', 'plugins', 'storages', PLUGIN_ID, EXPORT_PREFIX,
  );
  fs.mkdirSync(exportDir, { recursive: true });

  fs.writeFileSync(path.join(exportDir, 'cv.yml'), 'experience:\n  - position: Engineer\n');
  fs.writeFileSync(path.join(exportDir, 'profile.yml'), 'name: Test Person\n');
  fs.writeFileSync(path.join(exportDir, 'personal.yml'), 'music:\n  title: Music\n');
  fs.writeFileSync(path.join(exportDir, 'publication_overrides.yml'), 'key2024:\n  selected: true\n');

  if (withManifest) {
    fs.writeFileSync(
      path.join(exportDir, 'manifest.json'),
      manifestContent
        ?? JSON.stringify({ exported_at: '2026-01-01T00:00:00.000Z', counts: { experience: 1 } }, null, 2),
    );
  }
  if (withBlog) {
    fs.mkdirSync(path.join(exportDir, 'blog'), { recursive: true });
    fs.writeFileSync(path.join(exportDir, 'blog', '2026-01-02-a-post.md'), '---\ntitle: "A Post"\n---\n');
  }
  return path.join(root, 'graph');
}

/** A site checkout with generated files that must survive the sync untouched. */
const SENTINELS = {
  '_data/cv.yml': 'cv:\n  - title: GENERATED BY TRANSFORM\n',
  '_data/icon_map.yml': 'up: assets/img/logos/up.png\n',
  '_posts/2020-01-01-existing.md': '---\ntitle: Existing\n---\n',
  '_bibliography/papers.bib': '@article{key2024}\n',
};

function makeSite(root) {
  const siteDir = path.join(root, 'site');
  for (const [rel, content] of Object.entries(SENTINELS)) {
    const abs = path.join(siteDir, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content);
  }
  return siteDir;
}

/**
 * Run sync.sh, throwing on a non-zero exit. `stderrOut`, when given, collects
 * the script's stderr so a test can assert on warnings.
 */
function runSync(args, env = {}, stderrOut = null) {
  const result = spawnSync('bash', [SYNC_SH, ...args], {
    encoding: 'utf8',
    // Strip inherited GRAPH_DIR/SITE_DIR so the test controls them entirely.
    // Node omits undefined-valued keys when building the child's environment.
    env: { ...process.env, GRAPH_DIR: undefined, SITE_DIR: undefined, ...env },
  });
  if (stderrOut) stderrOut.push(result.stderr);
  if (result.status !== 0) {
    throw new Error(`sync.sh exited ${result.status}\n${result.stderr}`);
  }
  return result.stdout;
}

describe('sync.sh', () => {
  let tmp;

  beforeEach(() => {
    tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'alfolio-sync-'));
  });

  afterEach(() => {
    fs.rmSync(tmp, { recursive: true, force: true });
  });

  describe('destination', () => {
    test('copies every exported file into _incoming/', () => {
      const graph = makeGraph(tmp);
      const site = makeSite(tmp);

      runSync(['--graph', graph, '--site', site]);

      const incoming = path.join(site, '_incoming');
      for (const f of ['cv.yml', 'profile.yml', 'personal.yml', 'publication_overrides.yml', 'manifest.json']) {
        expect(fs.existsSync(path.join(incoming, f))).toBe(true);
      }
      expect(fs.existsSync(path.join(incoming, 'blog', '2026-01-02-a-post.md'))).toBe(true);
    });

    test('copies file contents verbatim', () => {
      const graph = makeGraph(tmp);
      const site = makeSite(tmp);

      runSync(['--graph', graph, '--site', site]);

      const exportDir = path.join(graph, '.logseq/plugins/storages', PLUGIN_ID, EXPORT_PREFIX);
      const incoming = path.join(site, '_incoming');
      for (const f of ['cv.yml', 'manifest.json']) {
        expect(fs.readFileSync(path.join(incoming, f), 'utf8'))
          .toBe(fs.readFileSync(path.join(exportDir, f), 'utf8'));
      }
    });

    test('keeps the manifest named manifest.json', () => {
      const graph = makeGraph(tmp);
      const site = makeSite(tmp);

      runSync(['--graph', graph, '--site', site]);

      expect(fs.existsSync(path.join(site, '_incoming', 'manifest.json'))).toBe(true);
      expect(fs.existsSync(path.join(site, '_data', 'export_manifest.json'))).toBe(false);
    });
  });

  describe('generated directories are never written', () => {
    test('leaves _data/, _posts/ and _bibliography/ byte-identical', () => {
      const graph = makeGraph(tmp);
      const site = makeSite(tmp);

      runSync(['--graph', graph, '--site', site]);

      for (const [rel, original] of Object.entries(SENTINELS)) {
        expect(fs.readFileSync(path.join(site, rel), 'utf8')).toBe(original);
      }
    });

    test('creates no files outside _incoming/', () => {
      const graph = makeGraph(tmp);
      const site = makeSite(tmp);

      const before = listFiles(site);
      runSync(['--graph', graph, '--site', site]);
      const added = listFiles(site).filter((f) => !before.includes(f));

      expect(added.length).toBeGreaterThan(0);
      for (const f of added) {
        expect(f.startsWith('_incoming/')).toBe(true);
      }
    });

    test('does not create _data/ or _posts/ when the site lacks them', () => {
      const graph = makeGraph(tmp);
      const site = path.join(tmp, 'bare-site');
      fs.mkdirSync(site, { recursive: true });

      runSync(['--graph', graph, '--site', site]);

      expect(fs.existsSync(path.join(site, '_data'))).toBe(false);
      expect(fs.existsSync(path.join(site, '_posts'))).toBe(false);
      expect(fs.existsSync(path.join(site, '_incoming', 'cv.yml'))).toBe(true);
    });
  });

  describe('refuses to guess a destination', () => {
    test('exits non-zero when --site is omitted', () => {
      const graph = makeGraph(tmp);

      expect(() => runSync(['--graph', graph])).toThrow();
    });

    test('exits non-zero when the site directory does not exist', () => {
      const graph = makeGraph(tmp);

      expect(() => runSync(['--graph', graph, '--site', path.join(tmp, 'nope')])).toThrow();
    });

    test('reports a flag given without a value instead of failing silently', () => {
      const site = makeSite(tmp);

      const stderr = [];
      expect(() => runSync(['--site', site, '--graph'], {}, stderr)).toThrow();
      expect(stderr.join('')).toMatch(/--graph requires a path/);
    });

    test('honours SITE_DIR from the environment', () => {
      const graph = makeGraph(tmp);
      const site = makeSite(tmp);

      runSync(['--graph', graph], { SITE_DIR: site });

      expect(fs.existsSync(path.join(site, '_incoming', 'cv.yml'))).toBe(true);
    });
  });

  describe('incomplete exports', () => {
    test('exits non-zero when the export directory is missing', () => {
      const site = makeSite(tmp);

      expect(() => runSync(['--graph', path.join(tmp, 'no-graph'), '--site', site])).toThrow();
      expect(fs.existsSync(path.join(site, '_incoming'))).toBe(false);
    });

    test('exits non-zero when manifest.json is missing', () => {
      const graph = makeGraph(tmp, { withManifest: false });
      const site = makeSite(tmp);

      expect(() => runSync(['--graph', graph, '--site', site])).toThrow();
      expect(fs.existsSync(path.join(site, '_incoming'))).toBe(false);
    });

    // The summary block runs after every copy has already happened, so it must
    // never decide the exit status: a wrapper reading the code would otherwise
    // treat a completed sync as a failure and possibly re-run it.
    test('still succeeds when manifest.json is not valid JSON', () => {
      const graph = makeGraph(tmp, { manifestContent: 'NOT JSON{' });
      const site = makeSite(tmp);

      const stderr = [];
      expect(() => runSync(['--graph', graph, '--site', site], {}, stderr)).not.toThrow();

      expect(fs.existsSync(path.join(site, '_incoming', 'cv.yml'))).toBe(true);
      expect(fs.readFileSync(path.join(site, '_incoming', 'manifest.json'), 'utf8')).toBe('NOT JSON{');
      expect(stderr.join('')).toMatch(/manifest\.json may be malformed/);
    });

    test('succeeds when there are no blog posts', () => {
      const graph = makeGraph(tmp, { withBlog: false });
      const site = makeSite(tmp);

      runSync(['--graph', graph, '--site', site]);

      expect(fs.existsSync(path.join(site, '_incoming', 'cv.yml'))).toBe(true);
      expect(fs.existsSync(path.join(site, '_incoming', 'blog'))).toBe(false);
    });
  });
});

/** Every file under `dir`, as paths relative to it. */
function listFiles(dir, prefix = '') {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) out.push(...listFiles(path.join(dir, entry.name), rel));
    else out.push(rel);
  }
  return out;
}
